### ISSUE TITLE
blpop not compiling

### ISSUE THREAD

**Issue by repomaa** [stefanwille/crystal-redis#98]
There's an issue with the `blpop` command. When trying to use it i get the following error:

```
In lib/redis/src/redis/commands.cr:917:47

 917 | result[0] = without_namespace("#{result.first}")
                                               ^----
Error: undefined method 'first' for Redis::Future
```

**Comment by repomaa** [comment]
Specifically: using blpop inside a multi

**Comment by stefanwille** [comment]
Yes, this is a bug in a MULTI context. brpop has the same bug.

This bug is difficult to fix. I am not sure yet how I will do it.

**Comment by kostya** [comment]
it should compile in 2.7.0, but seems in multi it will be runtime error, can you provide example and reopen if still fails.
